CREATE TABLE users(id INT PRIMARY KEY AUTO_INCREMENT,full_name VARCHAR(60) NOT NULL,email VARCHAR(100) NOT NULL,password VARCHAR(200) NOT NULL,bearer_token VARCHAR(300) DEFAULT NULL);

CREATE TABLE cars(id INT PRIMARY KEY AUTO_INCREMENT,user_id INT NOT NULL,nickname VARCHAR(50) NOT NULL,description VARCHAR(300) NOT NULL,speed INT DEFAULT 0,hvac TINYINT DEFAULT 0,stateOfCharge INT DEFAULT 0, latitude VARCHAR(15) DEFAULT NULL,longitude VARCHAR(15) DEFAULT NULL);

CREATE TABLE sessions(id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, session_id INT NOT NULL, speed INT DEFAULT 0,hvac TINYINT DEFAULT 0,stateOfCharge INT DEFAULT 0, latitude VARCHAR(15) DEFAULT "0.0",longitude VARCHAR(15) DEFAULT "0.0", created_at datetime default CURRENT_TIMESTAMP);
