version: "3.8"
services:
  db:
    build: ./.docker/db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    restart: always
  web:
    build: 
      context: .
      dockerfile: .docker/node/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
    restart: on-failure
