version: "3.8"
services:
  db:
    build: ./.docker/db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rimac
    restart: always
  web:
    build: 
      context: .
      dockerfile: .docker/node/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - db
    restart: on-failure
